name: Generate circular manifest

on:
  push:
    branches: [ "main" ]
    paths:
      - "GC*_Merged.pdf"
      - ".github/workflows/generate-circular-manifest.yml"

permissions:
  contents: write

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate manifest
        run: |
          set -euo pipefail

          OUT="circular-manifest.json"

          # Match: GC + (YYYY + 0MMDD) + _Merged.pdf
          # Example: GC202600116_Merged.pdf
          files=$(find . -maxdepth 1 -type f \( -iname "GC?????????_Merged.pdf" \) -printf "%f\n" | sort)

          ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          {
            echo "{"
            echo "  \"updatedAt\": \"${ts}\","
            echo "  \"files\": ["
            first=1
            while IFS= read -r f; do
              [ -z "$f" ] && continue
              if [ $first -eq 1 ]; then
                first=0
              else
                echo ","
              fi
              printf "    %s" "\"$f\""
            done <<< "$files"
            echo ""
            echo "  ]"
            echo "}"
          } > "$OUT"

      - name: Commit manifest
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add circular-manifest.json
          git diff --cached --quiet || git commit -m "Update circular manifest"
          git push
